#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

#define HAVE_MALLOC
#undef  HAVE_MALLOC

#define HCI_ACL_PAYLOAD_SIZE          1024
#define HCI_INCOMING_PRE_BUFFER_SIZE  4
#define MAX_NR_GATT_CLIENTS           1
#define MAX_NR_HCI_CONNECTIONS        1
#define MAX_NR_L2CAP_CHANNELS         4
#define MAX_NR_L2CAP_SERVICES         2
#define MAX_NR_SM_LOOKUP_ENTRIES      3
#define MAX_NR_WHITELIST_ENTRIES      1
#define MAX_NR_LE_DEVICE_DB_ENTRIES   4

#define ENABLE_BLE
#define ENABLE_LOG_ERROR
#define ENABLE_LOG_INFO

#endif
